# Generated by Django 4.1.3 on 2022-11-24 04:31

import api.utils.image_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imageaws',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('document', models.FileField(upload_to=api.utils.image_utils.rename_image)),
            ],
            options={
                'verbose_name_plural': 'Aws Image',
            },
        ),
    ]
